# Generated by Django 4.2.7 on 2024-01-02 22:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="logistics_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Jan"),
                    (2, "Feb"),
                    (3, "Mar"),
                    (4, "Apr"),
                    (5, "May"),
                    (6, "Jun"),
                    (7, "Jul"),
                    (8, "Aug"),
                    (9, "Sept"),
                    (10, "Oct"),
                    (11, "Nov"),
                    (12, "Dec"),
                ],
                default=0,
            ),
        ),
    ]
