# Generated by Django 4.2.7 on 2024-01-09 23:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_logistics_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="details_template",
            field=models.TextField(
                blank=True,
                help_text="This text will be pre-filled into the registration form. A quick way to include questions that are not part of the default form.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logistics_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Jan"),
                    (2, "Feb"),
                    (3, "Mar"),
                    (4, "Apr"),
                    (5, "May"),
                    (6, "Jun"),
                    (7, "Jul"),
                    (8, "Aug"),
                    (9, "Sept"),
                    (10, "Oct"),
                    (11, "Nov"),
                    (12, "Dec"),
                ],
                default=0,
                help_text="What month of the campaign should this be counted as? Must match the event start or end date.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logistics_periods",
            field=models.DecimalField(
                decimal_places=2, help_text="How many long rests?", max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logistics_year",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="What year of the campaign is this event in? Must match the event start or end date.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="When should the Register button go away, in the chapter's local timezone?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_open",
            field=models.DateTimeField(
                blank=True,
                help_text="When should the Register button be shown, in the chapter's local timezone?",
                null=True,
            ),
        ),
    ]
