# Generated by Django 4.2.7 on 2024-01-16 18:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_details_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="canceled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
