# Generated by Django 4.2.7 on 2024-01-17 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_canceled_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventRegistration",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
