# Generated by Django 4.2.7 on 2024-02-03 14:45

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="nickname",
        ),
        migrations.AddField(
            model_name="membership",
            name="birthdate",
            field=models.DateField(
                default=datetime.date(2024, 2, 3),
                help_text="Your date of birth. Games have special rules regarding minors.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membership",
            name="emergency_contacts",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Please provide one or more emergency contacts.",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="legal_name",
            field=models.CharField(
                default="?",
                help_text="Your legal name, for legal reasons.",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membership",
            name="medical",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Do you have any allergies or other medical conditions that you would like staff to know about?",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="my_guardian",
            field=models.TextField(
                blank=True,
                default="",
                help_text="If you are a minor or otherwise require a guardian, who will serve as your guardian at games?",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="my_minors",
            field=models.TextField(
                blank=True,
                default="",
                help_text="If you are a guardian for a minor you are responsible for at game, identify them here.",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name you prefer to use. We'll use it whenever possible.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="pronouns",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What are your pronouns? Optional.",
                max_length=20,
            ),
        ),
    ]
