# Generated by Django 4.2.7 on 2024-02-04 18:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_membership_nickname_membership_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
