# Generated by Django 4.2.7 on 2024-02-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_membership_nickname_membership_birthdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="joined",
        ),
    ]
