# Generated by Django 4.2.7 on 2024-02-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_membership_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="joined",
        ),
    ]
