# Generated by Django 4.1.3 on 2022-12-03 17:32

import django.db.models.deletion
import rules.contrib.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_open", models.BooleanField(default=False)),
                ("owners", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_open", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="game.game",
                    ),
                ),
                ("owners", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("game", "slug")},
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GameRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title to display for this user (GM, Customer Service, etc)",
                        max_length=50,
                    ),
                ),
                (
                    "manager",
                    models.BooleanField(
                        default=False,
                        help_text="Can grant roles, sets game details, and manages chapters.",
                    ),
                ),
                (
                    "auditor",
                    models.BooleanField(
                        default=False, help_text="Can view data in any chapter."
                    ),
                ),
                (
                    "rules_staff",
                    models.BooleanField(
                        default=False, help_text="Can create and modify rulesets."
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="game.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "user")},
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChapterRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title to display for this user (GM, Customer Service, etc)",
                        max_length=50,
                    ),
                ),
                (
                    "manager",
                    models.BooleanField(
                        default=False,
                        help_text="Can grant roles at the chapter level and set chapter details.",
                    ),
                ),
                (
                    "logistics_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Can manage events, grant rewards, etc.",
                    ),
                ),
                (
                    "plot_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Can view characters, write plot notes, etc.",
                    ),
                ),
                (
                    "tavern_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Set event meal information, view meal choices, see food allergy data.",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="game.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("chapter", "user")},
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
