# Generated by Django 4.1.3 on 2022-12-03 19:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="site",
        ),
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.TextField(default="Game"),
        ),
    ]
