# Generated by Django 4.1.7 on 2023-04-06 20:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_ruleset"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
