# Generated by Django 4.2.7 on 2024-01-02 22:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="timezone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
