# Generated by Django 4.2.7 on 2024-01-09 17:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_chapter_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="timezone",
            field=models.CharField(
                blank=True, help_text="e.g. 'America/Denver'", max_length=50
            ),
        ),
    ]
