# Generated by Django 4.2.7 on 2024-01-17 23:34

import django.db.models.deletion
import rules.contrib.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("character", "0004_undostackentry"),
        ("game", "0008_alter_chapter_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("location", models.TextField(blank=True)),
                (
                    "details_template",
                    models.TextField(
                        blank=True,
                        help_text="This text will be pre-filled into the registration form. A quick way to include questions that are not part of the default form.",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("canceled_date", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_open",
                    models.DateTimeField(
                        blank=True,
                        help_text="When should the Register button be shown, in the chapter's local timezone? Leave blank to open immediately.",
                        null=True,
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="When should the Register button go away, in the chapter's local timezone? Leave blank to open until end-of-event.",
                        null=True,
                    ),
                ),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
                (
                    "logistics_periods",
                    models.DecimalField(
                        decimal_places=2, help_text="How many long rests?", max_digits=4
                    ),
                ),
                (
                    "logistics_year",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="What year of the campaign is this event in? Must match the event start or end date.",
                    ),
                ),
                (
                    "logistics_month",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Jan"),
                            (2, "Feb"),
                            (3, "Mar"),
                            (4, "Apr"),
                            (5, "May"),
                            (6, "Jun"),
                            (7, "Jul"),
                            (8, "Aug"),
                            (9, "Sept"),
                            (10, "Oct"),
                            (11, "Nov"),
                            (12, "Dec"),
                        ],
                        default=0,
                        help_text="What month of the campaign should this be counted as? Must match the event start or end date.",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="game.campaign",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="game.chapter",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_npc", models.BooleanField()),
                ("details", models.TextField(blank=True)),
                ("registered_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("canceled_date", models.DateTimeField(blank=True, null=True)),
                ("attended", models.BooleanField(default=False)),
                (
                    "attended_periods",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_registrations",
                        to="character.character",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_registrations",
                        to="game.event",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.sheet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event", "user"], name="game-event-user-idx"),
                    models.Index(
                        fields=["event", "character"], name="game-event-character-idx"
                    ),
                ],
                "unique_together": {("event", "user")},
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["campaign", "chapter", "logistics_year", "logistics_month"],
                name="game-campaign-year-month-idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("event_end_date__gte", models.F("event_start_date"))),
                name="end_date_gte_start",
                violation_error_message="End date must not be before start date.",
            ),
        ),
    ]
