# Generated by Django 4.2.7 on 2024-01-18 01:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_event_eventregistration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="timezone",
            field=models.CharField(help_text="e.g. 'America/Denver'", max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(
                blank=True,
                help_text="Physical address, maybe with a map link. Markdown enabled.",
            ),
        ),
    ]
