# Generated by Django 4.2.7 on 2024-01-28 19:47

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0010_alter_chapter_timezone_alter_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="game.event",
            ),
        ),
    ]
