# Generated by Django 4.2.7 on 2024-01-31 22:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0011_alter_eventregistration_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="logistics_periods",
            field=models.DecimalField(
                decimal_places=2,
                default=4,
                help_text="How many long rests?",
                max_digits=4,
            ),
        ),
    ]
