# Generated by Django 4.2.7 on 2024-01-31 23:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0013_event_daygame_logistics_periods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="is_daygaming",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="is_npc",
            field=models.BooleanField(default=False),
        ),
    ]
