# Generated by Django 4.2.7 on 2024-02-01 03:21

from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0014_eventregistration_is_daygaming_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("daygame_logistics_periods__gte", Decimal("0"))),
                name="daygame_periods_nonneg",
                violation_error_message="Number of daygame logistics periods must be non-negative.",
            ),
        ),
    ]
