# Generated by Django 4.2.7 on 2024-02-01 03:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0015_event_daygame_periods_nonneg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventregistration",
            name="is_daygaming",
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="attendance",
            field=models.IntegerField(
                choices=[(0, "Full Game"), (1, "Day Game")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_start_date",
            field=models.DateTimeField(),
        ),
    ]
