# Generated by Django 4.2.7 on 2024-02-01 15:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0016_remove_eventregistration_is_daygaming_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Standard"), (1, "Module"), (2, "Tavern"), (3, "Meetup")],
                default=0,
            ),
        ),
    ]
