# Generated by Django 4.2.7 on 2024-02-02 13:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0017_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Standard"), (1, "Module"), (2, "Tavern")], default=0
            ),
        ),
    ]
