# Generated by Django 4.2.7 on 2024-02-02 15:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0019_event_cabin_allowed_event_tenting_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="payment_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
