# Generated by Django 4.2.7 on 2024-02-02 15:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0020_eventregistration_payment_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="payment_details",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Payment information. Markdown enabled. Recommend linking to payment pages.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Physical address, maybe with a map link. Markdown enabled.",
            ),
        ),
    ]
