# Generated by Django 4.2.7 on 2024-02-09 22:10

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0024_eventreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="started",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 2, 9, 22, 10, 10, 274645, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
