# Generated by Django 4.2.10 on 2024-02-20 21:50

from decimal import Decimal

from django.db import migrations
from django.db import models

import camp.game.models.game_models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0025_eventreport_started"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="game-campaign-year-month-idx",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="data",
        ),
        migrations.RemoveField(
            model_name="event",
            name="logistics_month",
        ),
        migrations.RemoveField(
            model_name="event",
            name="logistics_year",
        ),
        migrations.AddField(
            model_name="campaign",
            name="engine_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="start_year",
            field=models.IntegerField(default=camp.game.models.game_models._this_year),
        ),
        migrations.AddField(
            model_name="event",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(blank=True, default="Campaign", max_length=100),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="daygame_logistics_periods",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2"),
                help_text="How many half-days for a daygamer? Set to zero to disallow daygaming. Must be less than the normal reward.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logistics_periods",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("4"),
                help_text="How many half days?",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_footer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["campaign", "chapter"], name="game-campaign-idx"
            ),
        ),
    ]
