# Generated by Django 4.2.10 on 2024-02-27 01:03

import django.db.models.deletion
import rules.contrib.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0026_remove_event_game_campaign_year_month_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="award_applied_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="award_applied_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp when this award was applied to the character record, if it was applied.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PlayerCampaignData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_data",
                        to="game.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "campaign")},
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
