# Generated by Django 4.2.10 on 2024-03-04 14:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0031_alter_award_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="applied_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
