# Generated by Django 4.2.10 on 2024-03-17 18:16

from django.db import migrations
from django.db import models

import camp.game.models.event_models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0033_eventreport_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventreport",
            name="task_id",
            field=models.CharField(
                blank=True,
                default=camp.game.models.event_models._task_uuid,
                help_text="Task ID used by the underlying task queue system.",
                max_length=100,
                null=True,
            ),
        ),
    ]
