# Generated by Django 5.2.5 on 2025-08-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0035_ruleset_remote_data_ruleset_remote_error_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventreport",
            name="task_id",
        ),
    ]
