# Generated by Django 4.1.7 on 2023-04-20 11:49

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_alter_chapter_unique_together_ruleset_enabled_and_more"),
        ("character", "0002_remove_character_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="game",
            field=models.ForeignKey(
                default=1,
                help_text="The game this character belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="game.game",
            ),
            preserve_default=False,
        ),
    ]
