# Generated by Django 4.2 on 2023-05-07 22:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0003_character_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="UndoStackEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("mutation", models.JSONField(blank=True, null=True)),
                ("previous_data", models.JSONField()),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="undo_stack",
                        to="character.sheet",
                    ),
                ),
            ],
        ),
    ]
