# Generated by Django 4.2.10 on 2024-02-27 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("character", "0005_character_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="discarded_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="discarded_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
