# Generated by Django 4.2.10 on 2024-03-12 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("character", "0006_character_discarded_by_character_discarded_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="discarded_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="discarded_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
